base_images:
  base:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
build_root:
  project_image:
    dockerfile_path: openshift/ci-operator/build-image/Dockerfile
#images:
#  - dockerfile_path: openshift/ci-operator/gitserver-image/Dockerfile
#    to: gitserver-image
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.15"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  commands: GOFLAGS="" make test
  container:
    from: src
- as: e2e-oncluster-test
  cluster_claim:
    architecture: amd64
    cloud: aws
    owner: serverless-ci
    product: ocp
    timeout: 1h30m0s
    version: "4.15"
  steps:
    test:
    - as: test
      commands: |
        openshift/cluster-prepare.sh
        openshift/e2e_oncluster_tests.sh
     # dependencies:
     #   - env: GITSERVER_IMAGE
     #     name: gitserver-image
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 30m0s
    workflow: generic-claim
zz_generated_metadata:
  branch: presumtest
  org: jrangelramos
  repo: func
